Change external links attributes to improve screen-readers experience
zopaUK/react-components pull request #667
Opened 2021-03-04 10:16 UTC by OlenaKashuba

- Add aria-label to announce the link purpose for screen readers
- Use title to warn a user that link opens in a new tab

The link will be announced like e.g. `Link, Twitter. Twitter opens in a new tab. You are currently on a Link.`

2021-03-04 15:49 UTC, moshie requested changes

2021-03-04 15:49 UTC, moshie commented on src/components/molecules/ZopaFooter/ZopaFooter.tsx
> +            title="Instagram"
Instagram opens up in a new tab?

2021-03-04 16:03 UTC, OlenaKashuba commented on src/components/molecules/ZopaFooter/ZopaFooter.tsx
> +            title="Instagram"
true, thanks

2021-03-04 19:59 UTC, poteirard approved these changes

2021-03-04 20:16 UTC, moshie approved these changes

2021-03-05 09:13 UTC, merged

2021-03-11 12:04 UTC, poteirard commented
:tada: This PR is included in version 4.39.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@zopauk/react-components/v/4.39.0)
- [GitHub release](https://github.com/zopaUK/react-components/releases/tag/v4.39.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: