fix(navbar): hamburger menu in mobile view had wrong border radius (8px)
zopaUK/react-components pull request #724
Opened 2021-07-27 10:13 UTC by Gabss405

changed it to 0px, it has to explicitly say 0px otherwise inherits 8px border radius from Button component 
<img width="519" alt="Screenshot 2021-07-27 at 11 11 19" src="https://user-images.githubusercontent.com/67011746/127137139-92927a44-c40e-4b2d-aa2a-1bca6bda2ccd.png">

2021-07-27 10:13 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/zopaUK/react-components?pullRequest=724) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/zopaUK/react-components?pullRequest=724) before we can accept your contribution.<br/><hr/>**Gabor Halasz** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/zopaUK/react-components?pullRequest=724) it.</sub>

2021-07-27 11:21 UTC, emilfjellstrom requested changes
[Amend] Seems like you have to update the Snapshots, if you run `pnpm test -- -u` and push the updated snaps the CI should be happy

2021-07-27 14:07 UTC, emilfjellstrom requested changes

2021-07-27 14:20 UTC, emilfjellstrom approved these changes
LGTM

2021-07-27 16:02 UTC, poteirard commented on src/components/organisms/Navbar/Navbar/Navbar.tsx
> +  border-radius: 0px:
just being picky here :P But actually you don't need unit type for 0. So it can be `border-radius: 0;`

2021-07-28 07:33 UTC, poteirard approved these changes

2021-07-28 08:29 UTC, merged

2021-07-28 08:31 UTC, poteirard commented
:tada: This PR is included in version 4.43.16 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@zopauk/react-components/v/4.43.16)
- [GitHub release](https://github.com/zopaUK/react-components/releases/tag/v4.43.16)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: