Navbar cta fix
zopaUK/react-components pull request #734
Opened 2021-08-31 10:04 UTC by Gabss405

#722 

- rearranged style inheritance in Navbar.tsx, IconContainer is now div instead of button so no more default button styling unless withCTA or links is true

https://user-images.githubusercontent.com/67011746/131483678-6b49469d-2294-4ecd-9670-041503f83b6f.mov

2021-08-31 10:37 UTC, moshie requested changes

2021-08-31 10:37 UTC, moshie commented on src/components/organisms/Navbar/Navbar/Navbar.tsx
> +const IconContainer = styled.div`
the icon container still needs the aria attribute

2021-09-07 11:24 UTC, poteirard approved these changes

2022-11-30 10:08 UTC, poteirard commented
Closing as we have a new navbar now

2022-11-30 10:08 UTC, closed without merging